### PR TITLE
Merge ROS client interface and make README more pretty

### PR DESCRIPTION
**Pull request by marcomasa**
Added the client lib that i implemented for the older action interface (old action msg names).

Also re-organized the readme and added some more detailed install instructions

### CODE REVIEW

**Comment by marcomasa** [comment]
merge conflicts are resolved in my files, just use them completely

**Comment by daniel86** [comment]
Did you have a look at the diff? every file is changed, something went wrong. Definitely I cannot review this pull request like it is. Please make more atomic pull request and check the diff to make it feasible for me doing a proper review

**Comment by marcomasa** [comment]
Pretty sure that is because I initially started my repo from the modal branch.

I merged your new dev branch yesterday and had to resolve some merge issues manually, but my version now builds (with the new action msgs).

I assume it just shows weird on github as all of my older commits relate to the outdated modal branch.
The main files i changed regarding your branch are:
- Cmakelist (include my client lib and test node)
- readme (merging my documentation structure)
- Adding my client files

I could try to seperate it into two newer PRs, or you try to check out my repo version and test some stuff (verify its still your version).
What do you prefer?

**Comment by daniel86** [comment]
Yes might be the case that it is related to switching branches. I bet there is some git magic to make it right.
I definitely will not merge with such a change set, only the stuff that you really changed should be part of it.
And best to make for each different thing you did change an individual request such that reviewing can be done more easily.

**Comment by marcomasa** [comment]
closing due to new PR that can auto-merge ( #398 )

**Pull request closed without merging**
