### PR TITLE
Update setup

### PR DESCRIPTION
**Pull request by artnie**
Add instructions for the manual update of swi-prolog and mongodb.
Remove old knowrob-all.rosinstall since it uses old java deps.
Add command to launch the CLI for queries.

### CODE REVIEW

**Comment by sasjonge** [comment]
Maybe it would be better to move the installation tutorial for mongo and swipl into the wiki to keep the readme cleaner

**Comment by artnie** [comment]
Moved the install hints to the bottom of the readme. Maybe that's good enough? If you still insist, I'll put it into the wiki instead, and link to it in the readme.

**Comment by artnie** [comment]
bump

**Comment by sasjonge** [comment]
> bump
> 
> please tell if the setup still needs to go into the wiki, or if it can stay at the bottom of the readme.

I think it's okay to leave it there, but can you add a hyperlink instead of writing "see Further Information"?

**Review by sasjonge — APPROVED** [review]
Looks good to me.

**Pull request merged**
